#JPA
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: false
  mvc:
    view:
      prefix: /templates
      suffix: .html
  jackson:
    serialization:
      fail-on-empty-beans: false

#H2
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#    driver-class-name: org.h2.Driver
#    username: h2
#    password: h2
#server:
#  port: 8080

## my local postgres db
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: XABP123890

#db for docker
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
