version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    container_name: app
    build:
      context: services/app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  js:
    image: 'my-js-app'
    container_name: js
    build:
      context: services/js
      dockerfile: Dockerfile
    ports:
      - "8080:80"


