version: '3.8'

services:
  app:
    image: 'app_image:latest'
    container_name: app
    build:
      context: services/app
      dockerfile: Dockerfile
    environment:
      - PORT=8091
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: 'postgres_image:latest'
    container_name: db
    build:
      context: services/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5000:5432"
    volumes:
      - "db-data:/var/lib/postgresql/data"

  js:
    image: 'js_image:latest'
    container_name: js
    build:
      context: services/js
      dockerfile: Dockerfile
    ports:
      - "80:80"

volumes:
  db-data:


